import {test,expect} from './fixtures';
test('login, create, edit, delete and logout a show',async({page})=>{
 await page.goto('/login');await page.getByLabel('E-mail',{exact:true}).fill('e2e@example.test');await page.getByLabel('Senha',{exact:true}).fill('Revel-test-6w#Q9!Fz2026');await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page).toHaveURL(/\/admin/);
 await page.getByLabel('Título',{exact:true}).fill('E2E show');await page.getByLabel('Cidade',{exact:true}).fill('Bauru');await page.getByLabel('Local',{exact:true}).fill('Local de teste');await page.getByLabel('Data e hora').fill('2030-01-01T20:00');await page.getByLabel('Publicado na agenda').check();await page.getByRole('button',{name:'Salvar show'}).click();await expect(page.getByText('Show salvo.',{exact:true})).toBeVisible();
 const row=page.locator('.admin-show-list article').filter({hasText:'E2E show'});await expect(row).toBeVisible();await row.getByRole('button',{name:'Editar'}).click();await page.getByLabel('Título',{exact:true}).fill('E2E edited');await page.getByRole('button',{name:'Salvar show'}).click();await expect(page.getByText('E2E edited',{exact:true})).toBeVisible();
 page.once('dialog',dialog=>dialog.accept());await page.locator('.admin-show-list article').filter({hasText:'E2E edited'}).getByRole('button',{name:'Excluir'}).click();await expect(page.getByText('E2E edited',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Sair'}).click();await expect(page).toHaveURL(/\/login/);
});
test('queues a show offline and replays once on reconnection',async({page,context})=>{
 await page.goto('/login');await page.getByLabel('E-mail',{exact:true}).fill('e2e@example.test');await page.getByLabel('Senha',{exact:true}).fill('Revel-test-6w#Q9!Fz2026');await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page).toHaveURL(/\/admin/);
 await context.setOffline(true);await page.getByLabel('Título',{exact:true}).fill('Offline E2E');await page.getByLabel('Cidade',{exact:true}).fill('Bauru');await page.getByLabel('Local',{exact:true}).fill('Teste');await page.getByLabel('Data e hora').fill('2030-02-01T20:00');await page.getByRole('button',{name:'Salvar show'}).click();await expect(page.getByText('Alteração salva neste dispositivo.',{exact:true})).toBeVisible();
 await context.setOffline(false);await expect(page.getByText('Offline E2E',{exact:true})).toBeVisible({timeout:15000});expect(await page.getByText('Offline E2E',{exact:true}).count()).toBe(1);await page.getByRole('button',{name:'Sair'}).click();await expect(page).toHaveURL(/\/login/);expect(await page.evaluate(()=>localStorage.getItem('revel-session-user'))).toBeNull();
});
test('refreshes another authenticated editor through realtime events',async({page,browser})=>{
 const other=await browser.newContext();const second=await other.newPage();for(const tab of [page,second]){await tab.goto('http://localhost:3000/login');await tab.getByLabel('E-mail',{exact:true}).fill('e2e@example.test');await tab.getByLabel('Senha',{exact:true}).fill('Revel-test-6w#Q9!Fz2026');await tab.getByRole('button',{name:'Entrar',exact:true}).click();await expect(tab).toHaveURL(/\/admin/);}
 await page.getByLabel('Título',{exact:true}).fill('Realtime E2E');await page.getByLabel('Cidade',{exact:true}).fill('Bauru');await page.getByLabel('Local',{exact:true}).fill('Teste');await page.getByLabel('Data e hora').fill('2030-03-01T20:00');await page.getByRole('button',{name:'Salvar show'}).click();await expect(second.getByText('Realtime E2E',{exact:true})).toBeVisible({timeout:8000});await other.close();
});
test('wipes private cached data and queued writes when logging out offline',async({page,context})=>{
 await page.goto('/login');await page.getByLabel('E-mail',{exact:true}).fill('e2e@example.test');await page.getByLabel('Senha',{exact:true}).fill('Revel-test-6w#Q9!Fz2026');await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page).toHaveURL(/\/admin/);await page.evaluate(()=>navigator.serviceWorker.ready);await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await context.setOffline(true);await page.getByLabel('Título',{exact:true}).fill('Logout pending E2E');await page.getByLabel('Cidade',{exact:true}).fill('Bauru');await page.getByLabel('Local',{exact:true}).fill('Teste');await page.getByLabel('Data e hora').fill('2030-03-01T20:00');await page.getByRole('button',{name:'Salvar show'}).click();await expect(page.getByText('Alteração salva neste dispositivo.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Sair'}).click();await expect.poll(()=>page.evaluate(()=>localStorage.getItem('revel-session-user'))).toBeNull();
 await expect(page.getByRole('heading',{name:'REVEL / Offline'})).toBeVisible();const counts=await page.evaluate(()=>new Promise<{queue:number;cache:number}>((resolve,reject)=>{const open=indexedDB.open('revel-offline');open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result;const tx=db.transaction(['queue','cache']);const queue=tx.objectStore('queue').count();const cache=tx.objectStore('cache').count();tx.oncomplete=()=>{resolve({queue:queue.result,cache:cache.result});db.close();};};}));expect(counts).toEqual({queue:0,cache:0});await context.setOffline(false);await page.goto('/login');await expect.poll(()=>page.evaluate(()=>localStorage.getItem('revel-pending-logout'))).toBeNull();
});
test('persists authenticated preferences across browser contexts',async({page,browser})=>{
 await page.goto('/login');await page.getByLabel('E-mail',{exact:true}).fill('e2e@example.test');await page.getByLabel('Senha',{exact:true}).fill('Revel-test-6w#Q9!Fz2026');await page.getByRole('button',{name:'Entrar',exact:true}).click();await expect(page).toHaveURL(/\/admin/);await page.goto('/');await page.getByRole('button',{name:'Tema claro'}).click();await expect.poll(async()=>page.evaluate(async()=>{const result=await fetch('/api/v1/preferences');return (await result.json()).theme;})).toBe('light');
 const other=await browser.newContext();const second=await other.newPage();await second.goto('http://localhost:3000/login');await second.getByLabel('E-mail',{exact:true}).fill('e2e@example.test');await second.getByLabel('Senha',{exact:true}).fill('Revel-test-6w#Q9!Fz2026');await second.getByRole('button',{name:'Entrar',exact:true}).click();await expect(second.locator('html')).toHaveAttribute('data-theme','light');await other.close();
});
